apiVersion: frontend-forge.kubesphere.io/v1alpha1
kind: FrontendIntegration
metadata:
  name: fi-nested-menu-demo
  annotations:
    kubesphere.io/creator: admin
spec:
  displayName: Nested Menu Demo
  enabled: true
  menus:
    - displayName: Ops Center
      key: ops
      placement: workspace
      type: organization
      children:
        - displayName: Inspect Tasks
          key: inspecttasks
        - displayName: Ops Guide
          key: ops-guide
  pages:
    - key: inspecttasks
      type: crdTable
      crdTable:
        names:
          plural: inspecttasks
          kind: InspectTask
        version: v1alpha2
        group: kubeeye.kubesphere.io
        scope: Cluster
        columns:
          - key: name
            title: NAME
            enableSorting: true
            render:
              type: text
              path: metadata.name
          - key: updateTime
            title: CREATION_TIME
            enableHiding: true
            enableSorting: true
            render:
              type: time
              path: metadata.creationTimestamp
              format: local-datetime
    - key: ops-guide
      type: iframe
      iframe:
        src: http://example.test/ops-guide
